### ISSUE TITLE
"refdb_contams" workflow exits with error if outputblacklist does not already exist

### ISSUE THREAD

**Issue by jvollme** [jvollme/mdmcleaner#18]
command:
```
mdmcleaner.py refdb_contams -c mdmcleaner.config test_overview_refdb_ambiguities.tsv -o new_blacklist_additions.tsv -t 8 
```
result:
```
Traceback (most recent call last):
  File "/home/ww5070/temp_binsaga/sagabin_refiner/lib/mdmcleaner.py", line 316, in <module>
    main()
  File "/home/ww5070/temp_binsaga/sagabin_refiner/lib/mdmcleaner.py", line 224, in main
    configs = config_object(args, read_blacklist = True)
  File "/home/ww5070/temp_binsaga/sagabin_refiner/lib/mdmcleaner.py", line 94, in __init__
    self.blacklist = self.read_blacklistfiles()
  File "/home/ww5070/temp_binsaga/sagabin_refiner/lib/mdmcleaner.py", line 137, in read_blacklistfiles
    with openfile(blacklistfile) as blf:
  File "/home/ww5070/temp_binsaga/sagabin_refiner/lib/misc.py", line 26, in openfile
    filehandle = open(infilename, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'new_blacklist_additions.tsv'
```

**Comment by jvollme** [comment]
this actually did nor refer to the output-blacklist, but to an expected input-blacklist (set in the local config file) of the same name. Now made workflow skip all input-blacklists that it can't find
